version: '3.3'
services:
    server:
        container_name: vaultwarden
        restart: always
        volumes:
            - '/docker/appdata/vaultwarden:/data/'
        ports:
            - '81:80'
            - '3012:3012'
        environment:
            - WEBSOCKET_ENABLED=true
            - ADMIN_TOKEN=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        image: vaultwarden/server
