version: '3.3'
services:
    wg-easy:
        environment:
            - WG_HOST=45.33.88.16
            - 'PASSWORD=SVmZuZ#274xk4X'
        volumes:
            - '/docker/appdata/wg-easy/:/etc/wireguard'
        ports:
            - '51820:51820/udp'
            - '51821:51821/tcp'
        restart: unless-stopped
        image: weejewel/wg-easy
